# Generated by Django 4.2.6 on 2023-10-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_group_members_chat_recipient_alter_chat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
