# Generated by Django 4.2.6 on 2023-10-24 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_onlineuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlineuser',
            old_name='status',
            new_name='is_online',
        ),
    ]
